#
#  Copyright (c) 2010 - 2015, Intel Corporation.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms and conditions of the GNU General Public License,
#  version 2, as published by the Free Software Foundation.
#
#  This program is distributed in the hope it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#  more details.
#

ccflags-y += -DATOMISP_POSTFIX=\"css2401a0_legacy_v21\" -DATOMISP_FWNAME=\"shisp_2401a0_legacy_v21.bin\" -DISP2401
ISP2401 := y
postfix := css2401a0_legacy_v21

include $(srctree)/$(src)/../Makefile.common
